version: "3.6"

services:
    telefoni-site:
        container_name: "telefoni-api"
        build: .
        volumes:
            - ../telefoni-za-vas:/var/www/
            - ../log:/var/www/storage/logs
        ports:
            - "8080:80"
    db:
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
        volumes:
            - ../db:/var/lib/mysql
    adminer:
        image: adminer
        restart: always
        ports:
            - 8081:8080
